### ISSUE TITLE
Documentatie bestaande api

### ISSUE THREAD

**Issue by Badlapje** [daanpape/stumon-breakout-server#1]
Daan, begrijp ik het goed dat elke folder een module is?  

Is er ergens documentatie wat de bestaande api is die wordt blootgesteld naar externe applicaties?

**Comment by daanpape** [comment]
Het board pushed nieuwe tags naar een server, hoe dit gebeurt kan je in deze source file terug vinden https://github.com/daanpape/stumon-breakout-server/blob/master/stumon/stumon_longrunner.c Via het configuratiebestand /etc/config/dpt-breakout-server kan je de adressen aanpassen zonder dat je moet hercompileren. Je kan via telnet op het bakje inloggen op 192.168.1.1 indien je via rechstreekse wifi bent aangemeld.
